title: c3-tmp-r-day-night
hero_image: images/banner.png
description: c3-tmp-r-day-night description
version: 4
listed: false
copyedit: false
last_tested: "2019-03-17"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
